package com.nighthawk.aetha_backend.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "notification_settings") // MongoDB collection name
public class NotificationSettings {

    @Id
    private String id; // Unique ID generated by MongoDB
    private String userId; // Unique user ID

    private boolean commentRepliesOnsite;
    private boolean commentRepliesEmail;

    private boolean mentioningOnsite;
    private boolean mentioningEmail;

    private boolean privateMessagesEmail;
    private boolean newChaptersEmail;

    private boolean weeklyChapterSummaryEmail;
    private boolean newCommentInChapterOnsite;

    private boolean reviewsOnsite;

    public String getUserId() {
        return userId;
    }
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public boolean isCommentRepliesOnsite() {
        return commentRepliesOnsite;
    }
    public void setCommentRepliesOnsite(boolean commentRepliesOnsite) {
        this.commentRepliesOnsite = commentRepliesOnsite;
    }

    public boolean isCommentRepliesEmail() {
        return commentRepliesEmail;
    }
    public void setCommentRepliesEmail(boolean commentRepliesEmail) {
        this.commentRepliesEmail = commentRepliesEmail;
    }

    public boolean isMentioningOnsite() {
        return mentioningOnsite;
    }
    public void setMentioningOnsite(boolean mentioningOnsite) {
        this.mentioningOnsite = mentioningOnsite;
    }

    public boolean isMentioningEmail() {
        return mentioningEmail;
    }
    public void setMentioningEmail(boolean mentioningEmail) {
        this.mentioningEmail = mentioningEmail;
    }

    public boolean isPrivateMessagesEmail() {
        return privateMessagesEmail;
    }
    public void setPrivateMessagesEmail(boolean privateMessagesEmail) {
        this.privateMessagesEmail = privateMessagesEmail;
    }

    public boolean isNewChaptersEmail() {
        return newChaptersEmail;
    }
    public void setNewChaptersEmail(boolean newChaptersEmail) {
        this.newChaptersEmail = newChaptersEmail;
    }

    public boolean isWeeklyChapterSummaryEmail() {
        return weeklyChapterSummaryEmail;
    }
    public void setWeeklyChapterSummaryEmail(boolean weeklyChapterSummaryEmail) {
        this.weeklyChapterSummaryEmail = weeklyChapterSummaryEmail;
    }

    public boolean isNewCommentInChapterOnsite() {
        return newCommentInChapterOnsite;
    }
    public void setNewCommentInChapterOnsite(boolean newCommentInChapterOnsite) {
        this.newCommentInChapterOnsite = newCommentInChapterOnsite;
    }

    public boolean isReviewsOnsite() {
        return reviewsOnsite;
    }
    public void setReviewsOnsite(boolean reviewsOnsite) {
        this.reviewsOnsite = reviewsOnsite;
    }


}
