spring:
  application:
    name: aetha_backend
  data:
    mongodb:
      uri: mongodb+srv://aetha_dev:aethadev%401256@aetha-cluster.6wbuwdx.mongodb.net/aetha_db?retryWrites=true&w=majority&appName=aetha-cluster
      authentication-database: admin
      username: aetha_dev
      password: aethadev@1256
  security:
    user:
      name: admin
      password: adminpassword
  app:
    jwtSecret: 1a8a5fc2bae92e78ca36dc26642c6f8fa69af0683542bc365552284baf251fccs
    jwtExpiration: 86400000 # 24 hours
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

env:
  uploads:
    secret_key: "nVDjQCU0qiMFuyCa8lWMKKun4q5hciGjhkZrfezu5TI="
  imagekit:
    publicKey: "public_GCupctCpbthLRh/wP6eCY7dc0fE="
    privateKey: "private_jFKJDFznJQYotWykfHBJi5RuRyw="
    urlEndpoint: "https://ik.imagekit.io/aetha"