package com.nighthawk.aetha_backend.dto;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "notification_settings") // MongoDB collection name
public class NotificationSettingsDTO {

    @Id
    private String id; // Unique ID generated by MongoDB
    private String userId; // Unique user ID

    private boolean commentRepliesOnsite;
    private boolean commentRepliesEmail;

    private boolean mentioningOnsite;
    private boolean mentioningEmail;

    private boolean privateMessagesEmail;
    private boolean newChaptersEmail;

    private boolean weeklyChapterSummaryEmail;
    private boolean newCommentInChapterOnsite;

    private boolean reviewsOnsite;

    // Getters and setters

    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }

    public boolean isCommentRepliesOnsite() { return commentRepliesOnsite; }
    public void setCommentRepliesOnsite(boolean commentRepliesOnsite) { this.commentRepliesOnsite = commentRepliesOnsite; }

    // Other getters and setters for each field
}
